    !!com.example.app.properties.PropertiesData
    appiumProperties:
      platformName: android
      deviceName: device
      udid: emulator-5554
      app: C:/Users/Wahyu Nusantara Azis/Downloads/Programs/app-debug_v.1.0.apk
      automationName: UIAutomator2
      newCommandTimeout: 120
      autoGrantPermissions: true
